"""Fail-closed selection of independently versioned source and publication data."""

from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import sys
from pathlib import Path


def validate_selection(source: str, data: str, publication_source: str, expected_source: str) -> None:
    for value in (source, data, publication_source, expected_source):
        if re.fullmatch(r"[a-f0-9]{40}", value) is None:
            raise ValueError("Publication selection requires full source and data revisions.")
    if source != expected_source:
        raise ValueError("The completion validated an older source revision; refuse deployment.")
    if publication_source != source:
        raise ValueError("The selected publication was not generated by the current source revision.")


def _git(repository: Path, *arguments: str) -> str:
    executable = shutil.which("git")
    if executable is None:
        raise ValueError("Git is required to verify publication selection.")
    result = subprocess.run(  # noqa: S603 - fixed executable and arguments, never a shell.
        [executable, "-C", str(repository), *arguments], capture_output=True, text=True, check=True, timeout=30,
    )
    return result.stdout.strip()


def verify_current(repository: Path, source: str, data: str, trigger_data: str | None = None) -> None:
    """Recheck remote heads immediately before publication; never run data-branch code."""
    validate_selection(source, data, source, source)
    heads = _git(repository, "ls-remote", "origin", "refs/heads/main", "refs/heads/radar-data")
    selected = {row.split()[1]: row.split()[0] for row in heads.splitlines() if len(row.split()) == 2}
    if selected.get("refs/heads/main") != source or selected.get("refs/heads/radar-data") != data:
        raise ValueError("Source or operational data advanced; refuse a stale deployment.")
    if trigger_data is not None:
        if re.fullmatch(r"[a-f0-9]{40}", trigger_data) is None:
            raise ValueError("A writer completion must identify its exact data revision.")
        _git(repository, "merge-base", "--is-ancestor", trigger_data, data)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repository", type=Path, default=Path.cwd())
    parser.add_argument("--source", required=True)
    parser.add_argument("--data", required=True)
    parser.add_argument("--publication-source", required=True)
    parser.add_argument("--expected-source", required=True)
    parser.add_argument("--trigger-data")
    options = parser.parse_args(argv)
    try:
        validate_selection(options.source, options.data, options.publication_source, options.expected_source)
        verify_current(options.repository, options.source, options.data, options.trigger_data)
    except (ValueError, OSError, subprocess.SubprocessError) as error:
        print(f"Publication selection refused: {error}", file=sys.stderr)
        return 1
    print("Exact protected source and operational data selection verified.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
